<?php

/**
 * @file
 * Control access to members only files.
 */

/**
 * Implements hook_menu().
 */
function kidneys_member_files_menu() {

  $items = array();

  $items['member-file'] = array(
    'title' => 'Member File',
    'page callback' => 'kidneys_member_files_page',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Page callback.
 */
function kidneys_member_files_page() {
  $file = $_GET['file'];
  $roles = $_GET['roles'];

  if (!isset($file)) {
    return;
  }

  drupal_goto('/system/files/members/' . $file);
}

/**
 * Implements hook_file_download().
 *
 * Needed in order to allow file download for private files.
 * From https://gist.github.com/kamkejj/9259121.
 */
function kidneys_member_files_file_download($uri) {
  watchdog('kidneys_member_files_1', $uri);
  // Get the file record based on the URI. If not in the database just return.
  $files = file_load_multiple(array(), array('uri' => $uri));
  if (count($files)) {
    foreach ($files as $item) {
      // Since some database servers sometimes use a case-insensitive comparison
      // by default, double check that the filename is an exact match.
      if ($item->uri === $uri) {
        $file = $item;
        break;
      }
    }
  }
  watchdog('kidneys_member_files_2', $uri);
  if (!isset($file)) {
    watchdog('kidneys_member_files_3', $uri);
    return;
  }
  watchdog('kidneys_member_files_4', $uri);
  $headers = file_get_content_headers($file);

  // Set the header to initiate a download.
  $headers['Content-Disposition'] = 'attachment; filename=' . drupal_get_filename('module', $uri);

  file_transfer($uri, $headers);
}
