<?php

/**
 * @file
 * Control access to members only files.
 */

/**
 * Implements hook_menu().
 */
function kidneys_member_files_menu() {

  $items = array();

  $items['member-file'] = array(
    'title' => 'Member File',
    'page callback' => 'kidneys_member_files_page',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  $items['admin/config/user-interface/member-redirect'] = array(
    'title' => 'Member files config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kidneys_member_files_admin_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback.
 */
function kidneys_member_files_admin_form($form, &$form_state) {

  $form['kidneys_member_redirect'] = array(
    '#type' => 'textfield',
    '#title' => t('Redirect for non members accessing files'),
    '#required' => TRUE,
    '#default_value' => variable_get('kidneys_member_redirect', '/'),
  );

  return system_settings_form($form);
}

/**
 * Page callback.
 */
function kidneys_member_files_page() {
  global $user;
  $file = $_GET['file'];
  $roles = $_GET['roles'];
  $verified = FALSE;
  if ($user->uid == 1 || array_filter($user->roles, function($element) { return (strpos(strtolower($element), 'member:') !== FALSE) ? TRUE : FALSE; })) {
    drupal_goto('/sites/default/files/' . $file);
  }
  drupal_goto(variable_get('kidneys_member_redirect', '/'));
}

/**
 * Implements hook_file_download().
 *
 * Needed in order to allow file download for private files.
 * From https://gist.github.com/kamkejj/9259121.
 */
 /*
function kidneys_member_files_file_download($uri) {
  global $user;
  watchdog('kidneys_member_files_1', $uri);
  // Get the file record based on the URI. If not in the database just return.
  $files = file_load_multiple(array(), array('uri' => $uri));
  if (count($files)) {
    foreach ($files as $item) {
      // Since some database servers sometimes use a case-insensitive comparison
      // by default, double check that the filename is an exact match.
      if ($item->uri === $uri) {
        $file = $item;
        break;
      }
    }
  }
  watchdog('kidneys_member_files_2', $uri);
  if (!isset($file)) {
    watchdog('kidneys_member_files_3', $uri);
    return;
  }
  watchdog('kidneys_member_files_4', $uri);
  //$headers = file_get_content_headers($file);

  // Set the header to initiate a download.
  //$headers['Content-Disposition'] = 'attachment; filename=' . drupal_get_filename('module', $uri);

  //file_transfer($uri, $headers);

  //$mime = file_get_mimetype($uri);

  $verified = FALSE;

  if (strpos($uri, 'public://members') === 0) {
    watchdog('kidneys_member_files_5', $uri);
    if (array_filter($user->roles, function($element) { return (strpos(strtolower($element), 'member:') !== FALSE) ? TRUE : FALSE; })) {
      return array(
        'Content-type' => file_get_mimetype($uri),
        'Content-Length' => filesize($uri),
      );
    }
    else {
      watchdog('kidneys_member_files_5', $uri);
      drupal_goto('/');
    }
  }
  else {
    return -1;
  }

}
*/
